# znippy-cli/Cargo.toml

[package]
name = "znippy-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
anyhow = "1.0.98"
compress = { path = "../compress" }
decompress = { path = "../decompress" }
znippy-common = { path = "../znippy-common" }
env_logger = "0.11.8"
